FROM node:20-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x /app/docker-entrypoint.sh

EXPOSE 5173

ENTRYPOINT ["/bin/sh", "/app/docker-entrypoint.sh"]
